### PR TITLE
Do not cons anzu mode line construct onto non-list mode line

### LINKED ISSUE #126: Anzu breaks mode line when using Info+ package
Info+ is a package that, among other things, provides
`Info-breadcrumbs-in-mode-line-mode`, which simplifies the `*info*`
buffer mode line into simply a list of breadcrumbs describing the
current node.  However, the `mode-line-format` it uses is a simple
string, not a list.  This means that when `anzu-mode` is enabled, it
can cause the following error when exiting isearch, due to an
incorrect assumption in `anzu--reset-mode-line`:

```
setq: Wrong type argument: listp, #("(dir)Top" 5 8 (face mode-line-buffer-id help-echo "mouse-1: Scroll back, mouse-2: Scroll forward, mouse-3: Menu" mouse-face mode-line-highlight local-map (keymap (mode-line keymap (mouse-2 . Info-mouse-scroll-up) (mouse-1 . Info-mouse-scroll-down) (mouse-3 keymap (Info-set-breadcrumbs-depth menu-item "Set Breadcrumbs Depth" Info-set-breadcrumbs-depth :help "Set depth of breadcrumbs to show in the mode-line") (Info-breadcrumbs-in-mode-line-mode menu-item "Toggle Breadcrumbs" Info-breadcrumbs-in-mode-line-mode :help "Toggle displaying breadcrumbs in the Info mode-line" :button (:toggle . Info-breadcrumbs-in-mode-line-mode)) (separator "--") (Info-next menu-item "Next Node" Info-next :visible nil :help "Go to the next node") (Info-prev menu-item "Previous Node" Info-prev :visible nil :help "Go to the previous node") "Breadcrumbs in Mode Line")))))
```

### PR DESCRIPTION
**Pull request by bcc32**
Fix #126.

### CODE REVIEW

**Comment by LemonBreezes** [comment]
Looks good to me. It seems reasonable to assume that if a package sets `mode-line-format` to a string, it wants to "own" `mode-line-format`.

**Comment by bcc32** [comment]
@LemonBreezes sorry for the ping, would you be willing to tag a new release that includes this fix, so that it be available on nongnu elpa?

**Comment by LemonBreezes** [comment]
> @LemonBreezes sorry for the ping, would you be willing to tag a new release that includes this fix, so that it be available on nongnu elpa?

Let me know if the latest commit does not do the trick.

**Comment by bcc32** [comment]
0.66 works, thanks!

**Pull request merged**
